project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Fundamental"
            file: content/01_journal/01_fundamental.qmd
          - text: "02 Machine Learning Regression"
            file: content/01_journal/02_ml_regression.qmd
          - text: "03 Machine LEarning H2O 1"
            file: content/01_journal/03_ml_h2o_1.qmd
          - text: "04 Machine Learning H2O 2 & Performance Measures"
            file: content/01_journal/04_ml_h2o_2_and_performance_measures.qmd
          - text: "05 Black box model with lime"
            file: content/01_journal/05_black_box_lime.qmd
          - text: "06 Deep Learning"
            file: content/01_journal/06_deep_learning.qmd
          - text: "tEst pAge"
            file: content/01_journal/Test_Training.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto